### ISSUE TITLE
只遍历了课程列表却没有下载

### ISSUE THREAD

**Issue by ohmyray** [lemisky/boxuegu#2]
只遍历了课程列表却没有下载，产生了一个课程json文件就退出程序了

**Comment by lemisky** [comment]
你好，

是这样的，下载视频分为两步，
1.拉取视频信息，boxuegu.bat
2.根据json,下载视频 boxuegu.bat d video.json

注意：json中的视频信息有有效期，如果第二步出错，请重新走第一步，拉取视频不可中断，但下载视频阶段是可以中断。

**Comment by lemisky** [comment]
有问题可继续issue
