### ISSUE TITLE
为什么在linux上面测试是下载的一样的视频

### ISSUE THREAD

**Issue by ascarl2010** [lemisky/boxuegu#3]
是不是windows和liunx的换行符不一样导致的，希望能使用\r\n进行区别

**Comment by lemisky** [comment]
你好，可以说的具体点吗，

下载的是一样的视频，什么意思？

视频是根据你填写的课程id来的

**Comment by ascarl2010** [comment]
你可以在linux上测试一下  跑jar包

**Comment by lemisky** [comment]
Windows上正常？Linux下载的视频一样的？

**Comment by lemisky** [comment]
前阵子发现确实存在这个问题, 已经修改
