### ISSUE TITLE
视频下载失败，Exception in thread "pool-2-thread-40" net.m3u8.Exception.M3u8Exception: 连接超时！

### ISSUE THREAD

**Issue by istudyRun** [lemisky/boxuegu#4]
下载视频不停重试，抛异常Exception in thread "pool-2-thread-40" net.m3u8.Exception.M3u8Exception: 连接超时！

最后合并的视频全是0kb，大佬，请问是哪里的问题？麻烦指点一下

**Comment by lemisky** [comment]
我刚刚试了下, 似乎一切正常.
我尝试重新 拉取视频信息 

PS C:\Users\admin> cd C:\Users\admin\Desktop\boxuegu
PS C:\Users\admin\Desktop\boxuegu> .\boxuegu.bat

C:\Users\admin\Desktop\boxuegu>java -jar boxuegu.jar
data/Python入门公开课 : courseId : 1229
        资料链接.TXT
        python入门公开课
                python公开课视频0218.
C:\Users\admin\Desktop\boxuegu>java -jar boxuegu.jar d .\data\Python入门公开课.json
开始下载资料 : video/Python入门公开课/资料/资料链接.TXT
video/Python入门公开课/资料/资料链接.TXT : 下载完毕。

开始下载        python公开课视频0218.
已用时1秒！     下载速度：9.690 MB/s
        已完成22个，还剩613个！
3.46%
已用时2秒！     下载速度：7.460 MB/s
        已完成44个，还剩591个！
6.93%
已用时3秒！     下载速度：18.815 MB/s
        已完成87个，还剩548个！
13.70%
已用时4秒！     下载速度：21.578 MB/s
        已完成119个，还剩516个！
18.74%
已用时5秒！     下载速度：15.027 MB/s
        已完成142个，还剩493个！
22.36%
已用时6秒！     下载速度：14.173 MB/s
        已完成162个，还剩473个！
25.51%
已用时7秒！     下载速度：14.990 MB/s
        已完成189个，还剩446个！
29.76%
已用时8秒！     下载速度：15.225 MB/s
        已完成225个，还剩410个！
35.43%
已用时9秒！     下载速度：14.562 MB/s
        已完成247个，还剩388个！
38.90%
已用时10秒！    下载速度：14.208 MB/s
        已完成264个，还剩371个！
41.57%
已用时11秒！    下载速度：14.982 MB/s
        已完成283个，还剩352个！
44.57%
已用时12秒！    下载速度：14.854 MB/s
        已完成304个，还剩331个！
47.87%
已用时13秒！    下载速度：14.241 MB/s
        已完成327个，还剩308个！
51.50%
已用时14秒！    下载速度：14.756 MB/s
        已完成352个，还剩283个！
55.43%
已用时15秒！    下载速度：14.635 MB/s
        已完成372个，还剩263个！
58.58%
已用时16秒！    下载速度：14.097 MB/s
        已完成392个，还剩243个！
61.73%
已用时17秒！    下载速度：14.884 MB/s
        已完成421个，还剩214个！
66.30%
已用时18秒！    下载速度：14.913 MB/s
        已完成467个，还剩168个！
73.54%
已用时19秒！    下载速度：14.616 MB/s
        已完成487个，还剩148个！
76.69%
已用时20秒！    下载速度：14.801 MB/s
        已完成513个，还剩122个！
80.79%
已用时21秒！    下载速度：14.772 MB/s
        已完成538个，还剩97个！
84.72%
已用时22秒！    下载速度：14.006 MB/s
        已完成557个，还剩78个！
87.72%
已用时23秒！    下载速度：15.027 MB/s
        已完成577个，还剩58个！
90.87%
已用时24秒！    下载速度：14.619 MB/s
        已完成598个，还剩37个！
94.17%
已用时25秒！    下载速度：12.250 MB/s
        已完成631个，还剩4个！
99.37%
已用时26秒！    下载速度：125.369 KB/s
        已完成633个，还剩2个！
99.69%
已用时27秒！    下载速度：492.817 KB/s
        已完成634个，还剩1个！
99.84%
已用时28秒！    下载速度：42.383 KB/s
        已完成634个，还剩1个！
99.84%
已用时29秒！    下载速度：46.484 KB/s
        已完成634个，还剩1个！
99.84%
已用时30秒！    下载速度：72.461 KB/s
        已完成634个，还剩1个！
99.84%
已用时31秒！    下载速度：691.313 KB/s
        已完成635个，还剩0个！
100.00%
下载完成，正在合并文件！共635个！364.968 MB
视频合并完成，欢迎使用!

下载完毕???     python公开课视频0218.

所      有      任      务      完      成      !

检查视频与网站内容, 一致, 视频大小也是正常的

出现这种问题的原因是 xx.json 中的视频链接失效了, 重新拉取就可以了, 运行 `boxuegu.bat` 即可, 再 继续下载, 已经下载的会跳过, 但是请先删除异常的视频

**Comment by lemisky** [comment]
@istudyRun

**Comment by istudyRun** [comment]
我下载的是付费教程，能帮我测试一下吗？我从昨天就开始搞了，始终卡在那个超时异常那里，视频的分片下载的也不完整，最后合成的都是0kb的文件

**Comment by istudyRun** [comment]
xx.json文件都是拉取完了立马去下载视频，但每次都不行，要么是超时异常，要么不停地重试

**Comment by lemisky** [comment]
回复好快呀, 那你加我 微信吧 lemisky

**Comment by gitLinan** [comment]
同样的问题 可以加微信吗？ 也是不停地在重试

**Comment by gitLinan** [comment]
而且我看抓取的url 都是http的还在报SSL的异常 可能不是https证书检测有问题

**Comment by lemisky** [comment]
没有 crypt 相关包会报这个错误(解密加密 ts 文件时). 在ide中正常, 单独使用 可能会有这样的错误.
通过 安装 BellSoft.LibericaJDK11Full, 无需其他操作, 错误消失.
