### ISSUE TITLE
下载报错了，看下能解决吗

### ISSUE THREAD

**Issue by UIT2016wanghui** [lemisky/boxuegu#6]
第1获取链接重试！       http://cd15-ccd1-2.play.bokecc.com/flvs/78665FEF083498AB/2020-12-28/7493FC42684843C39C33DC5901307461-20.ts?video=10&t=1612293673&key=60A41CE36E180883DAC2D61DBF5AA299&tpl=10&tpt=112
已用时5秒！     下载速度：2.160 MB/s
第1获取链接重试！       http://cd15-ccd1-2.play.bokecc.com/flvs/78665FEF083498AB/2020-12-28/7493FC42684843C39C33DC5901307461-20.ts?video=26&t=1612293673&key=60A41CE36E180883DAC2D61DBF5AA299&tpl=10&tpt=112
第1获取链接重试！       http://cd15-ccd1-2.play.bokecc.com/flvs/78665FEF083498AB/2020-12-28/7493FC42684843C39C33DC5901307461-20.ts?video=14&t=1612293673&key=60A41CE36E180883DAC2D61DBF5AA299&tpl=10&tpt=112
第1获取链接重试！       http://cd15-ccd1-2.play.bokecc.com/flvs/78665FEF083498AB/2020-12-28/7493FC42684843C39C33DC5901307461-20.ts?video=30&t=1612293673&key=60A41CE36E180883DAC2D61DBF5AA299&tpl=10&tpt=112
第1获取链接重试！       http://cd15-ccd1-2.play.bokecc.com/flvs/78665FEF083498AB/2020-12-28/7493FC42684843C39C33DC5901307461-20.ts?video=4&t=1612293673&key=60A41CE36E180883DAC2D61DBF5AA299&tpl=10&tpt=112
第1获取链接重试！       http://cd15-ccd1-2.play.bokecc.com/flvs/78665FEF083498AB/2020-12-28/7493FC42684843C39C33DC5901307461-20.ts?video=12&t=1612293673&key=60A41CE36E180883DAC2D61DBF5AA299&tpl=10&tpt=112
        已完成0个，还剩24个！

**Comment by lemisky** [comment]
1。这是jdk中没有xxx组件的原因，总得来说就是jdk环境的差异导致的；
2。安装 BellSoft.LibericaJDK11Full
可解决此问题。
3。下载大型课，建议调整代码结构；
4。还有问题，加我微信吧，lemisky，备注；
5。说好今天早睡的😭

**Comment by lemisky** [comment]
@UIT2016wanghui  release中存在重复下载一个的问题, 请使用最新代码
